package org.apache.jsp.demos.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class _005f_005f_005fleft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 

 String examplePath=getServletConfig().getServletContext().getRealPath("/");
  
 if(!examplePath.endsWith(File.separator))
 {
 	examplePath+= File.separator ;
 }
 
 examplePath+=("demos"+File.separator+"templates"+File.separator);
 examplePath = examplePath.replace('\\','/');



      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"generator\" content=\"CHM Decoder by GridinSoft LLC   www.gridinsoft.com\"><link rel=\"StyleSheet\" href=\"___dtree.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"___dtree.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body * {font-size:12px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Generated by CHM Decoder (http://www.gridinsoft.com) -->\r\n");
      out.write("<div class=\"dtree\" style=\"height:101%;\">\r\n");
      out.write("<p><a href=\"javascript: d.openAll();\">open all</a> | <a href=\"javascript: d.closeAll();\">close all</a></p>\r\n");
      out.write("<script type=\"text/javascript\"><!--\r\n");
      out.write("d = new dTree(\"d\",\"");
      out.print(examplePath);
      out.write("\");\r\n");
      out.write("d.openNode(\"简表(JOR)在线演示\",\"\");\r\n");
      out.write("\td.openNode(\"功能演示\",\"\");\r\n");
      out.write("\t\td.openNode(\"表格与交叉表\",\"\");\r\n");
      out.write("\t\t\td.add(\"每一分组占一页\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/每一分组占一页.xml\");\r\n");
      out.write("\t\t\td.add(\"多数据集交叉表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/多数据集交叉表.xml\");\r\n");
      out.write("\t\t\td.add(\"行列并行分组交叉表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/行列并行分组交叉表.xml\");\r\n");
      out.write("\t\t\td.add(\"层次不等的交叉表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/层次不等的交叉表.xml\");\r\n");
      out.write("\t\t\td.add(\"按汇总值排序的交叉表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/按汇总值排序的交叉表.xml\");\r\n");
      out.write("\t\t\td.add(\"排名的交叉报表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/排名的交叉报表.xml\");\r\n");
      out.write("\t\t\td.add(\"多级交叉表\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/多级交叉表.xml\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\td.add(\"占比\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/占比.xml\");\r\n");
      out.write("\t\t\td.add(\"比去年增长\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/比去年增长.xml\");\r\n");
      out.write("\t\t\td.add(\"去年同期比\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/去年同期比.xml\");\r\n");
      out.write("\t\t\td.add(\"排行榜\",\"../../reportviewer?file=\",\"功能演示/表格与交叉表/排行榜.xml\");\r\n");
      out.write("\t\td.closeNode();\r\n");
      out.write("\t\td.openNode(\"脚本\",\"\");\r\n");
      out.write("\t\t\td.add(\"斑马条\",\"../../reportviewer?file=\",\"功能演示/脚本/斑马条.xml\");\r\n");
      out.write("\t\t\td.add(\"本页小计与累计\",\"../../reportviewer?file=\",\"功能演示/脚本/本页小计与累计.xml\");\r\n");
      out.write("\t\t\td.add(\"用脚本进行复杂统计\",\"../../reportviewer?file=\",\"功能演示/脚本/用脚本进行复杂统计.xml\");\r\n");
      out.write("\t\t\td.add(\"颜色告警\",\"../../reportviewer?file=\",\"功能演示/脚本/颜色告警.xml\");\r\n");
      out.write("\t\t\td.add(\"引入自定义脚本函数\",\"../../reportviewer?file=\",\"功能演示/脚本/引入自定义脚本函数.xml\");\r\n");
      out.write("\t\td.closeNode();\r\n");
      out.write("\t\td.openNode(\"特殊报表效果\",\"\");\r\n");
      out.write("\t\t\td.add(\"分栏报表\",\"../../reportviewer?file=\",\"功能演示/特殊报表效果/分栏报表.xml\");\r\n");
      out.write("\t\t\td.add(\"空行补足表格\",\"../../reportviewer?file=\",\"功能演示/特殊报表效果/空行补足表格.xml\");\r\n");
      out.write("\t\t\td.add(\"超链接主报表\",\"../../reportviewer?file=\",\"功能演示/特殊报表效果/超链接主报表.xml\");\r\n");
      out.write("\t\t\td.add(\"套打\",\"../../reportviewer?file=\",\"功能演示/特殊报表效果/套打.xml\");\r\n");
      out.write("\t\t\td.add(\"编码字典\",\"../../reportviewer?file=\",\"功能演示/特殊报表效果/编码字典.xml\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\td.closeNode();\r\n");
      out.write("\t\td.openNode(\"java对象数据源\",\"\");\r\n");
      out.write("\t\t\td.add(\"tablemodel数据源\",\"../../reportviewer?file=\",\"功能演示/java对象数据源/tablemodel数据源.xml\");\r\n");
      out.write("\t\t\td.add(\"resultset数据源\",\"../../reportviewer?file=\",\"功能演示/java对象数据源/resultset数据源.xml\");\r\n");
      out.write("\t\t\td.add(\"嵌套的java对象数据源\",\"../../reportviewer?file=\",\"功能演示/java对象数据源/嵌套的java对象数据源.xml\");\r\n");
      out.write("\t\td.closeNode();\r\n");
      out.write("\t\t\r\n");
      out.write("\td.openNode(\"统计图、条形码与图片\",\"\");\r\n");
      out.write("\t\t\td.add(\"交叉表到k线图\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/交叉表到k线图.xml\");\r\n");
      out.write("\t\t\td.add(\"条状图到饼图\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/条状图到饼图.xml\");\r\n");
      out.write("\t\t\td.add(\"面积图到普通报表\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/面积图到普通报表.xml\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\td.add(\"标签报表.条形码\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/标签报表.条形码.xml\");\r\n");
      out.write("\t\t\td.add(\"背景图片\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/背景图片.xml\");\r\n");
      out.write("\t\t\t\t\td.add(\"显示数据库图片字段\",\"../../reportviewer?file=\",\"功能演示/统计图、条形码与图片/显示数据库图片字段.xml\");\r\n");
      out.write("\t\td.closeNode();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\td.closeNode();\t\r\n");
      out.write("\td.openNode(\"其他行业报表\",\"\");\r\n");
      out.write("\t\td.add(\"政府统计表\",\"../../reportviewer?file=\",\"其他行业报表/政府统计表.xml\");\r\n");
      out.write("\t\td.add(\"政府月报\",\"../../reportviewer?file=\",\"其他行业报表/政府月报.xml\");\r\n");
      out.write("\t\td.add(\"外贸清单\",\"../../reportviewer?file=\",\"其他行业报表/外贸清单.xml\");\r\n");
      out.write("\t\td.add(\"外贸发票\",\"../../reportviewer?file=\",\"其他行业报表/外贸发票.xml\");\r\n");
      out.write("\t\td.add(\"外贸托委书\",\"../../reportviewer?file=\",\"其他行业报表/外贸托委书.xml\");\r\n");
      out.write("\t\td.add(\"外贸报关单\",\"../../reportviewer?file=\",\"其他行业报表/外贸报关单.xml\");\r\n");
      out.write("\t\td.add(\"销售客户档案\",\"../../reportviewer?file=\",\"其他行业报表/销售客户档案.xml\");\r\n");
      out.write("\t\td.add(\"教育就业率\",\"../../reportviewer?file=\",\"其他行业报表/教育就业率.xml\");\r\n");
      out.write("\t\td.add(\"财务资产负债表\",\"../../reportviewer?file=\",\"其他行业报表/财务资产负债表.xml\");\r\n");
      out.write("\t\td.add(\"财务利润表\",\"../../reportviewer?file=\",\"其他行业报表/财务利润表.xml\");\r\n");
      out.write("\t\td.add(\"保险汇总单\",\"../../reportviewer?file=\",\"其他行业报表/保险汇总单.xml\");\r\n");
      out.write("\t\td.add(\"保险月报表\",\"../../reportviewer?file=\",\"其他行业报表/保险月报表.xml\");\r\n");
      out.write("\t\td.add(\"保险业绩表\",\"../../reportviewer?file=\",\"其他行业报表/保险业绩表.xml\");\t\r\n");
      out.write("\td.closeNode();\r\n");
      out.write("d.closeNode();\t\r\n");
      out.write("\r\n");
      out.write("document.write(d);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("<p \\><hr size=\"1\" \\>\r\n");
      out.write("<font class=\"dtree\">杰创软件拥有版权</font>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
